# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0003_auto_20160111_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='object_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
